# Generated by Django 4.2.4 on 2024-01-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default=None, upload_to='meals'),
        ),
    ]
