# Generated by Django 4.2.4 on 2024-01-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_foodieuser_mealrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodieuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
