# Generated by Django 4.2.4 on 2024-01-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_foodieuser_username_alter_restaurant_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='discountedPrice',
            field=models.FloatField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(upload_to='meals/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='restaurants/'),
        ),
    ]
