# Generated by Django 4.2.4 on 2024-01-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meal_discountedprice_alter_meal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcategory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='categories/'),
        ),
    ]
